import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#25272E] text-white">
        <div className="flex flex-row gap-[8px] m-[8px] ">
            <Sidebar />
            <div className="flex flex-col gap-[8px] w-full">
              <Navbar/>
              {children}
            </div>
        </div>
        
        
      </body>
    </html>
  );
}
